title: PlantPal Project

**Project Links**

Title | Links
---------- | ---------
Prototype A | https://www.figma.com/file/JUAZeO1Rwqx1IvIUh4UuOR3j/PlantPal%3A-Plant-Care-Reminder-App?node-id=1%3A4
Prototype B | https://www.figma.com/file/JUAZeO1Rwqx1IvIUh4UuOR3j/PlantPal%3A-Plant-Care-Reminder-App?node-id=11%3A2
Final Prototype | https://www.figma.com/file/JUAZeO1Rwqx1IvIUh4UuOR3j/PlantPal%3A-Plant-Care-Reminder-App?node-id=254%3A818
Prototype in Video | https://www.figma.com/file/JUAZeO1Rwqx1IvIUh4UuOR3j/PlantPal%3A-Plant-Care-Reminder-App?node-id=295%3A891

theme: jekyll-theme-cayman
