title: PlantPal Project

#Team
Brenda Quach
Environmental Engineering
University of Colorado Boulder
contact: Brenda.Quach@colorado.edu

Victoria
Computer Science
University of Colorado Boulder
contact: Victoria.Orta@colorado.edu

theme: jekyll-theme-cayman
